### ISSUE TITLE
Diffuse model is hard to see

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#24]
@mewall could you help identify a good starting value for diffuse sigma?  The current default of 0.4 gives a weak signal, and I would prefer to show a clearer effect when the diffuse features are first toggled on.

**Comment by mewall** [comment]
@nksauter I think the value of 0.4 for sigma is reasonable. The main issue is that the default domain size of 100 nm leads to a spreading of the Bragg peak that hides the diffuse intensity in the images. Increasing the anisotropy factor to 3 decreases the value of gamma along one axis which leads to some visible streaked diffuse features. For this reason, I would recommend changing the default anisotropy factor to 3 in the viewer.


Along these lines, I think if the user wants to explore diffuse scattering it's clearer to see what's happening using a domain size of 1000 nm instead of 100 nm.

________________________________
From: nksauter ***@***.***>
Sent: Tuesday, May 9, 2023 11:39:04 AM
To: dermen/sim_erice
Cc: Wall, Michael E; Assign
Subject: [EXTERNAL] [dermen/sim_erice] Diffuse model is hard to see (Issue #24)


@mewall<https://urldefense.com/v3/__https://github.com/mewall__;!!Bt8fGhp8LhKGRg!F6F2R0y0_aPMDRx-DruMdMLumcgjhagczy6Ftgf305j20s2lT0c261j2xOyqmGfrPcgHb7VQrIBBZ0zWdOQhWMRu$> could you help identify a good starting value for diffuse sigma? The current default of 0.4 gives a weak signal, and I would prefer to show a clearer effect when the diffuse features are first toggled on.

**Comment by nksauter** [comment]
Keeping the diffuse sigma as is.
