### ISSUE TITLE
Bug in anisotropic diffuse scatter?

### ISSUE THREAD

**Issue by nksauter** [dermen/sim_erice#32]
Active diffuse scatter and set diffuse anisotropy to 3.0.  Bragg spots are now surrounded by diffuse halos oriented approximately vertically.  

Now repeated calls to "Randomize orientation" always preserve the vertical orientation of the halos.  This is contrary to the expected behavior with the shape of the halo tied to the lattice.

**Comment by mewall** [comment]
@nksauter I'm seeing that this bug is specific to using the "Randomize orientation" button. If I set the orientation manually using Rotation (z), the direction of the streaks changes as expected. I think it can probably be fixed by whoever implemented the randomize orientation method.

________________________________

**Comment by mewall** [comment]
@nksauter Probably it would be good for this button to just populate the selection boxes with whatever the x, y, and z rotation angles are, and then to reuse the code for the manual selection case. Right now the orientation of the simulation changes without updating the numbers in the selection boxes, so a screen shot of the whole window would show rotation angles that don't correspond to what's being shown.

________________________________
