### ISSUE TITLE
Diffuse halos wrong in rotation mode

### ISSUE THREAD

**Issue by irisdyoung** [dermen/sim_erice#44]
Laue group may not be passed correctly in rotation mode. Set this correctly in rotation mode.

**Comment by mewall** [comment]
Extra information: Switching back from rotation mode to stills mode also appears not to restore the correct laue group.

**Comment by nksauter** [comment]
+1 from the reviewer who also states this is a necessary fix.

**Comment by irisdyoung** [comment]
I'm not able to replicate the diffuse halos being correct after randomize orientation at all, although I thought that was fixed already. Do I need to be on a particular branch? Or am I misremembering?

**Comment by mewall** [comment]
I think it was never fixed in rotation mode. It should work OK in the stills mode.


________________________________
From: Iris Young ***@***.***>
Sent: Friday, May 26, 2023 3:59:25 PM
To: dermen/sim_erice
Cc: Wall, Michael E; Comment
Subject: [EXTERNAL] Re: [dermen/sim_erice] Diffuse halos wrong in rotation mode (Issue #44)


I'm not able to replicate the diffuse halos being correct after randomize orientation at all, although I thought that was fixed already. Do I need to be on a particular branch? Or am I misremembering?
